plugins {
    id "java"
    id "com.github.ben-manes.versions" version "0.64.0"
}

repositories {
    maven { url "https://jitpack.io" }
    mavenCentral()
    google()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

def jmeVersion = "3.9.0-stable"
def ouistitiVersion = "2.2.0"
def chimpUtilsVersion = "1.7.0"

dependencies {
    // ouistiti dependencies
    implementation "com.github.benckx.chimp-utils:chimp-utils-jme3:$chimpUtilsVersion"
    implementation "com.github.benckx.chimp-utils:chimp-utils-basics:$chimpUtilsVersion"

    // ouistiti camera manager
    implementation "com.github.benckx:ouistiti:$ouistitiVersion"

    // jme3 libs
    implementation "org.jmonkeyengine:jme3-core:$jmeVersion"
    implementation "org.jmonkeyengine:jme3-desktop:$jmeVersion"
    implementation "org.jmonkeyengine:jme3-lwjgl3:$jmeVersion"
}
